Use camelCase in IdentV4 and dagexch messages
Pin yarl to v1.5.1 as v1.6.0 breaks something in
aioipfs with URLs.

AppImage/dmg: use git tags from $TRAVIS_BRANCH and
verify miniconda/go-ipfs checksums

diff --git a/AppImage/galacteek-appimage-build b/AppImage/galacteek-appimage-build
--- a/AppImage/galacteek-appimage-build
+++ b/AppImage/galacteek-appimage-build
@@ -7,7 +7,7 @@
 
 COMMIT_SHORT=$(echo $TRAVIS_COMMIT|cut -c 1-8)
 
-MINICONDA_DIST="Miniconda3-py37_4.8.2-Linux-x86_64.sh"
+MINICONDA_DIST="Miniconda3-py37_4.8.3-Linux-x86_64.sh"
 GO_IPFS_VERSION=0.6.0
 GOIPFS_TGZ="go-ipfs_v${GO_IPFS_VERSION}_linux-amd64.tar.gz"
 GOIPFS_DISTURL="https://dist.ipfs.io/go-ipfs/v${GO_IPFS_VERSION}/${GOIPFS_TGZ}"
@@ -18,33 +18,55 @@ else
     G_VERSION=$1
 fi
 
-if [ "$TRAVIS_BRANCH" != "master" ]; then
-    echo "Short commit ID: ${COMMIT_SHORT}"
-    APPIMAGE_DEST="Galacteek-${COMMIT_SHORT}-x86_64.AppImage"
-    APPIMAGE_FULL_DEST="Galacteek-wasmer-${COMMIT_SHORT}-x86_64.AppImage"
+if [[ $TRAVIS_BRANCH =~ ^v([0-9].[0-9].[0-9]{1,2}) ]] ; then
+    echo "Using tag: $TRAVIS_BRANCH"
+    EVERSION=${BASH_REMATCH[1]}
+    APPIMAGE_DEST="Galacteek-${EVERSION}-x86_64.AppImage"
+    APPIMAGE_FULL_DEST="Galacteek-wasmer-${EVERSION}-x86_64.AppImage"
 else
-    APPIMAGE_DEST="Galacteek-${G_VERSION}-x86_64.AppImage"
-    APPIMAGE_FULL_DEST="Galacteek-wasmer-${G_VERSION}-x86_64.AppImage"
+    if [ "$TRAVIS_BRANCH" != "master" ]; then
+        echo "Short commit ID: ${COMMIT_SHORT}"
+        APPIMAGE_DEST="Galacteek-${COMMIT_SHORT}-x86_64.AppImage"
+        APPIMAGE_FULL_DEST="Galacteek-wasmer-${COMMIT_SHORT}-x86_64.AppImage"
+    else
+        APPIMAGE_DEST="Galacteek-${G_VERSION}-x86_64.AppImage"
+        APPIMAGE_FULL_DEST="Galacteek-wasmer-${G_VERSION}-x86_64.AppImage"
+    fi
 fi
 
 echo "Travis commit: ${TRAVIS_COMMIT}"
 echo "Building AppImage for version: ${G_VERSION}"
 
 if ! [ -e $MINICONDA_DIST ]; then
-    wget "https://repo.continuum.io/miniconda/${MINICONDA_DIST}"
+    wget "https://repo.anaconda.com/miniconda/${MINICONDA_DIST}"
+    md5=$(md5sum ${MINICONDA_DIST}|awk '{print $1}')
+
+    if [ "$md5" != "751786b92c00b1aeae3f017b781018df" ]; then
+        echo "${MINICONDA_DIST}: invalid checksum"
+        exit 1
+    else
+        echo "${MINICONDA_DIST}: checksum is valid"
+    fi
 fi
 
 if [ "$TRAVIS_BRANCH" = "catalyst-ipfs-dev" ]; then
-	# Compile from master
-	git clone https://github.com/ipfs/go-ipfs.git $HOME/go-ipfs.git
-	pushd $HOME/go-ipfs.git
-	make build
-	cp cmd/ipfs/ipfs $HOME/bin/ipfs
-	popd
+    # Compile from master
+    git clone https://github.com/ipfs/go-ipfs.git $HOME/go-ipfs.git
+    pushd $HOME/go-ipfs.git
+    make build
+    cp cmd/ipfs/ipfs $HOME/bin/ipfs
+    popd
 else
-	wget $GOIPFS_DISTURL
-	tar -C /tmp -xzvf ${GOIPFS_TGZ}
-	mv /tmp/go-ipfs/ipfs $HOME/bin/ipfs
+    wget $GOIPFS_DISTURL
+    sha=$(sha512sum ${GOIPFS_TGZ}|awk '{print $1}')
+
+    if [ "$sha" != "57e4ac078f4605e3e765c6c5a54fe6e7f45268fa7ec06fc54f03e0046643dff65718f6f143a67fe08c458a7c86e30b5a53c400bdb57b6a2122bdc5df1a4b8f33" ]; then
+        echo "${GOIPFS_TGZ}: invalid checksum"
+        exit 1
+    fi
+
+    tar -C /tmp -xzvf ${GOIPFS_TGZ}
+    mv /tmp/go-ipfs/ipfs $HOME/bin/ipfs
 fi
 
 APPDIR="galacteek.AppDir.${G_VERSION}"
